### ISSUE TITLE
New devices and firmwares

### ISSUE THREAD

**Issue by anisse** [hughsie/8bitdo-firmware#1]
New 8bitdo devices and firmwares have been released:
http://support.8bitdo.com/#tab2

Are pull requests welcome to add support for those ?

**Comment by hughsie** [comment]
Tracked here: https://github.com/hughsie/fwupd/issues/350

I'm happy for a PR if you have something that works, although I've requested hardware so we can ensure it works in all modes.

**Comment by anisse** [comment]
I was more interested in the retro receivers; could they become part of the scope ? (Since they're only used with another device)

**Comment by hughsie** [comment]
I'm happy to accept PRs, although I don't have the hardware and cannot test them obviously.
