### ISSUE TITLE
missing-firmware NES30/N30/F30 4.20

### ISSUE THREAD

**Issue by clach04** [hughsie/8bitdo-firmware#12]
missing-firmware

http://download.8bitdo.com/Firmware/Controller/N30+F30/

http://download.8bitdo.com/Firmware/Controller/N30+F30/N30+F30_Firmware_V4.20.zip is relatively new 17-May-2019, but seems to work fine :smile

Wasn't sure whether to post here or https://github.com/hughsie/lvfs-website/issues/224

**Comment by hughsie** [comment]
Could you do a PR for this repo please? Thanks.

**Comment by iGom** [comment]
I can't update my NES30 from 4.10 to 4.20

"No upgrades for NES30 Joystick: current version is 4.10: 4.10=same, 4.01=older, 4.00=older, 2.70=older, 2.69=older"
