### ISSUE TITLE
How do i find the GUID?

### ISSUE THREAD

**Issue by sigboe** [hughsie/8bitdo-firmware#14]
Trying to pack a new firmware file. I have done everything except make a new icon and finding the GUID for the device.

It's the `USB Retro Receiver`, if I get it to with `fwupdmgr` I will look into the `USB Retro Receiver for PS` (I don't own that one, but might get it since I got the PS classic just now)

`fwupdmgr get-devices` doesn't show it.

Here are the journalctl logs

```
#regular mode
juni 11 19:00:14 zig-pc-04 kernel: usb 1-1: new full-speed USB device number 41 using xhci_hcd
juni 11 19:00:14 zig-pc-04 kernel: usb 1-1: New USB device found, idVendor=045e, idProduct=028e, bcdDevice= 1.20
juni 11 19:00:14 zig-pc-04 kernel: usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
juni 11 19:00:14 zig-pc-04 kernel: usb 1-1: Product: 8BitDo Receiver
juni 11 19:00:14 zig-pc-04 kernel: usb 1-1: Manufacturer: 8BitDo
juni 11 19:00:14 zig-pc-04 kernel: usb 1-1: SerialNumber: Receiver     
juni 11 19:00:14 zig-pc-04 kernel: input: Microsoft X-Box 360 pad as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/input/input97

#dfu mode
juni 11 19:01:14 zig-pc-04 kernel: usb 1-1: new full-speed USB device number 42 using xhci_hcd
juni 11 19:01:14 zig-pc-04 kernel: usb 1-1: New USB device found, idVendor=0483, idProduct=5760, bcdDevice= 2.00
juni 11 19:01:14 zig-pc-04 kernel: usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
juni 11 19:01:14 zig-pc-04 kernel: usb 1-1: Product: 8Bitdo  
juni 11 19:01:14 zig-pc-04 kernel: usb 1-1: Manufacturer: 8BitdoJoy
juni 11 19:01:14 zig-pc-04 kernel: usb 1-1: SerialNumber: BootMod
juni 11 19:01:14 zig-pc-04 kernel: hid-generic 0003:0483:5760.0014: hiddev96,hidraw1: USB HID v1.10 Device [8BitdoJoy 8Bitdo  ] on usb-0000:00:14.0-1/input0
```

How do I get the GUID?

**Comment by hughsie** [comment]
The GUID format is defined in https://github.com/hughsie/fwupd/blob/master/plugins/ebitdo/README.md -- so in this case it would be the case of doing `appstream-util generate-guid "USB\VID_2DC8&PID_AB11"` (quotes important). Of course, the other thing you need to so is add a quirk in the ebitdo plugin to cause the device to be exposed in fwupd: https://github.com/hughsie/fwupd/blob/master/plugins/ebitdo/ebitdo.quirk

Thanks for your help with this.

**Comment by sigboe** [comment]
Great! I will try this tomorrow and report back!

**Comment by sigboe** [comment]
@hughsie I have another question `idVendor=045e, idProduct=028e` corresponds to an Xbox 360 controller that already exists. 

But I don't see how the it is distinguished from a real xbox controller. In the journalctl logs the product, manufacturer and serialnumber differs from a real.

I suppose I would only add the DFU mode then? The VendorID is also nicked from STMicroelectronics, but as far as I can tell every database I looked up online the product ID is unique there. That would require the user to put it into DFU mode then run fwupdmgr, but I suppose that would be preferable to wrongly caching Xbox360 controllers, and other 3rd party that would nick hat vid/pid.

What about the bcdDevice? I don't know how unique it is?
Can `appstream-util generate-guid` match for Product, Manufacturer, or Serial?

**Comment by sigboe** [comment]
solved by https://github.com/hughsie/8bitdo-firmware/pull/15
