### ISSUE TITLE
Switch tries to Access Amiibo on SN30 Pro

### ISSUE THREAD

**Issue by seanathan** [hughsie/8bitdo-firmware#7]
When playing games with active amiibo integration (such as Splatoon 2) the Switch regularly attempts to wait for Amiibo scans at certain points (like loadout screens etc)

Somehow, the SN30 Pro is telling the Switch that it has NFC / Amiibo functionality, so the switch tries to activate and poll the sensor.

This, of course, causes an error code "2115-0112", "An error occured while trying to access the amiibo. Please try again"

This issue does not occur on the NES30 Pro, and it never even tries to poll NFC.

Perhaps this is part of the hardware profile uploaded to the Switch when paired?

I'd love to help, but I can't quite figure out how to edit this yet.

**Comment by hughsie** [comment]
This repo is only used for the LVFS firmware upload, I think you need to contact the upstream developer. Sorry.
